### ISSUE TITLE
Reaper Configurator directs "Printed TAP" into Github's "CNC TAP" folder for extruders

### ISSUE THREAD

**Issue by PeterXQC** [APDMachine/Reaper#4]
**Describe the bug**
Reaper Configurator directs "Printed TAP" into Github's "CNC TAP" folder for extruders.

**To Reproduce**
1. Go to Reaper Configurator
2. Configure as:
    [Printed Tap](https://apdm.tech/?x=parts&step=1)
    [Rapido V2 UHF](https://apdm.tech/?x=parts&step=2&carriage=printed%20tap)
    [Orbiter V2.0](https://apdm.tech/?x=parts&step=3&carriage=printed%20tap&hotend=Rapido%20V2%20UHF)
    [MGN12H](https://apdm.tech/?x=parts&step=4&carriage=printed%20tap&hotend=Rapido%20V2%20UHF&extruder=Orbiter%20V2.0)
    [6MM](https://apdm.tech/?x=parts&step=5&carriage=printed%20tap&hotend=Rapido%20V2%20UHF&extruder=Orbiter%20V2.0&csize=12)
    [Tap](https://apdm.tech/?x=parts&step=6&carriage=printed%20tap&hotend=Rapido%20V2%20UHF&extruder=Orbiter%20V2.0&csize=12&belt=6)
    [Grill Type 2](https://apdm.tech/?x=parts&step=7&carriage=printed%20tap&hotend=Rapido%20V2%20UHF&extruder=Orbiter%20V2.0&csize=12&belt=6&probe=Tap)
    [1PC](https://apdm.tech/?x=parts&step=8&carriage=printed%20tap&hotend=Rapido%20V2%20UHF&extruder=Orbiter%20V2.0&csize=12&belt=6&probe=Tap&gtype=2)
    [Voron](https://apdm.tech/?x=parts&step=9&carriage=printed%20tap&hotend=Rapido%20V2%20UHF&extruder=Orbiter%20V2.0&csize=12&belt=6&probe=Tap&gtype=2&ginsert=1PC)
    [Yes](https://apdm.tech/?x=parts&step=10&carriage=printed%20tap&hotend=Rapido%20V2%20UHF&extruder=Orbiter%20V2.0&csize=12&belt=6&probe=Tap&gtype=2&ginsert=1PC&glogo=Voron)

**Expected behavior**
The list of STLs to download should direct to correct locations of this Repo

**Filename**
STL/Extruder Mounts/TAP/OrbiterV2.0 Printed TAP.stl Does Not Exist

**Comment by krautech** [comment]
Interesting, I'll take a look at this now.

Thank you for reporting. Ill keep you updated!

**Comment by krautech** [comment]
This should now be corrected. Please re-open if you continue to experience issues.
